### ISSUE TITLE
Let us know how this plays out

### ISSUE THREAD

**Issue by JesseTG** [alex-spataru/QAppKiller#1]
I'm sorry that you had to write this library in the first place; you deserve better for the work you did. I'm very curious about how this library helps resolve your payment issue; please post an update when this all blows over, I'd love to find out.

**Comment by alex-spataru** [comment]
Well, they payed me as soon as they saw the banner and noticed that their app stopped working. I just sent them the application code (with this library removed of course). The only downside is that I received a couple of insults from the same people that tried to take advantage of my work.

But the library worked perfectly for all intents & purposes 💯

**Comment by JesseTG** [comment]
> The only downside is that I received a couple of insults from the same people that tried to take advantage of my work.

I'm not surprised; if they were interested in being polite, they'd have just paid you at the appropriate time.

> But the library worked perfectly for all intents & purposes 💯

Glad to hear it. :+1:
